GET http://localhost:8080/users
###

GET http://localhost:8080/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYzYzU4ZWQzYzNlNGY2YjYzNjViMjAiLCJpYXQiOjE3MjcyNTM2NDQsImV4cCI6MTcyNzI1MzY3NH0.Is9WaK6EtgQyU037FXyYN55aBO27bcCABF-7vw4NlaA

###
POST http://localhost:5000/signin
Content-Type: application/json

{
    "email": "ngiang028@gmail.com",
    "password": "giang1309"
}

###
POST http://localhost:5000/refreshtoken
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYzYzU4ZWQzYzNlNGY2YjYzNjViMjAiLCJpYXQiOjE3MjcyNTM2MDYsImV4cCI6MTcyNzg1ODQwNn0.T5xySrslY9Cjc6mc-W3t2gRCsvWa-YWZcHLFb8wfw1E

###
POST http://localhost:5000/logout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYzYzU4ZWQzYzNlNGY2YjYzNjViMjAiLCJpYXQiOjE3MjcyNTM2MDYsImV4cCI6MTcyNzg1ODQwNn0.T5xySrslY9Cjc6mc-W3t2gRCsvWa-YWZcHLFb8wfw1E

