GET http://localhost:8080/users
###

GET http://localhost:8080/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYzYzU4ZWQzYzNlNGY2YjYzNjViMjAiLCJpYXQiOjE3Mjc1NDU1MzAsImV4cCI6MTcyNzU0NTU2MH0.Mcu1SbCym7zqQlzi2T9il3kl_uG1Ju3QGlQ1hLjSbEs

###
POST http://localhost:8080/signin
Content-Type: application/json

{
    "email": "ngiang175@gmail.com",
    "password": "giang1309"
}

###
POST http://localhost:8080/refreshtoken
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzFmMzg4MzJiZTUxNzFiOWQ4MzNlZWMiLCJpYXQiOjE3MzAxMDc1MTUsImV4cCI6MTczMDcxMjMxNX0.I6rqfoY_y4fO0wFHhnCKapq6oJ9l-MUNlUtRUClPDLg

###
POST http://localhost:8080/logout
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmYzYzU4ZWQzYzNlNGY2YjYzNjViMjAiLCJpYXQiOjE3MjcyNTM2MDYsImV4cCI6MTcyNzg1ODQwNn0.T5xySrslY9Cjc6mc-W3t2gRCsvWa-YWZcHLFb8wfw1E

